version: '3.5'

services:
  restapi:
    build: ./restapi
    ports:
      - "5002:5002"
    env_file:
      - .env

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on: 
      - restapi