services:
  webapp:
    build:
      context: webapp
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./webapp:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - restapi

  restapi:
    restart: always
    build:
      context: restapi
    volumes:
      - ./restapi:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    expose: 
      - 3000
  
networks:
  react-express: