version: '3.8'

services:
  restapi:
    build:
      context: ./restapi
    ports:
      - '5001:5001'
    env_file:
      - .env

  webapp:
    build:
      context: ./webapp
    ports:
      - '3000:3000'
    depends_on:
      - restapi
    env_file:
      - .env