version: '3.5'
services:
  restapi:
    image: ghcr.io/paulasuarezp/restapi:latest
    ports:
      - "5001:5001"
  webapp:
    image: ghcr.io/paulasuarezp/webapp:latest
    ports:
      - "3000:3000"
    depends_on: 
      - restapi