name: CI for TFG

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [published]

jobs:
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./webapp
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/webapp:latest
          build-args: |
            API_URI=${{ secrets.API_URI }}

  docker-push-restapi:
    name: Push restapi Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./restapi
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/restapi:latest
          build-args: |
            SSL_CERT=${{ secrets.SSL_CERT }}
            SSL_PRIVKEY=${{ secrets.SSL_PRIVKEY }}
  
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-restapi,docker-push-webapp]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create docker-compose.yml
      run: echo "${{ secrets.DOCKER_COMPOSE_DEPLOY }}" > docker-compose.yml

    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull   
          docker-compose up -d
