name: CI/CD for TFG

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [published]

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build webapp Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/webapp:latest ./webapp

      - name: Build restapi Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/restapi:latest ./restapi

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tag and push webapp Docker image to ACR
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/webapp:latest tfgbidmonuniverseregistry.azurecr.io/webapp:latest
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login tfgbidmonuniverseregistry.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push tfgbidmonuniverseregistry.azurecr.io/webapp:latest

      - name: Tag and push restapi Docker image to ACR
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/restapi:latest tfgbidmonuniverseregistry.azurecr.io/restapi:latest
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login tfgbidmonuniverseregistry.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push tfgbidmonuniverseregistry.azurecr.io/restapi:latest

  deploy-to-app-service:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-push-to-acr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Compose to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: BidMonUniverse
          slot-name: production
          images: |
            tfgbidmonuniverseregistry.azurecr.io/webapp:latest
            tfgbidmonuniverseregistry.azurecr.io/restapi:latest
          configuration-file: docker-compose.yml
